// Reading a storefront catalogue a GM typed, pasted or uploaded.
//
// **One implementation, on this side.** The example is generated by the window, because
// only the window has the sheet templates; the reading happens here, because this is what
// stores the result. A parser mirrored into both languages would be two things to keep in
// step for no gain - the preview a GM sees is a round trip to this function, so what they
// are shown is literally what would be stored.
//
// **Problems are collected, never thrown.** A GM with one bad row wants to know which row,
// not to be handed an exception and an empty screen. Everything below either parses or
// reports a line number, and one unreadable row never costs the other forty.
//
// Three input shapes, sniffed rather than declared:
//
//   JSON      - an object keyed by catalogue, or an array of rows each naming its own.
//               Sniffed carefully: a leading `[` is NOT enough, because `[weapons]` opens
//               a section in the other format. See looksLikeJson.
//   delimited - tabs if the file has them, otherwise commas, or semicolons where Excel's
//               regional settings produced them.
//
// The delimited reader does real RFC-4180 quoting rather than splitting on the separator.
// That is not fastidiousness: item names in this hobby contain commas, and the CharWN
// importer already carries a note about exports containing "Kit, Cyberdoc". An unquoted
// comma silently shifts every column after it, which is the kind of wrong that gets stored
// and believed.

/** A byte-order mark at the front of a file Excel saved. Invisible, and breaks the first header. */
const stripBom = (text) => (text.charCodeAt(0) === 0xfeff ? text.slice(1) : text);

/**
 * Which of the two formats this is.
 *
 * A leading `{` is JSON and nothing else is. A leading `[` is **not** enough on its own,
 * because the sectioned format opens with one too - `[weapons]` is a section header, not a
 * JSON array, and sniffing on the bracket alone read every example this app hands out as
 * broken JSON. So a `[` counts only when what follows it could start a JSON value.
 */
const looksLikeJson = (text) => {
  if (text.startsWith('{')) return true;
  if (!text.startsWith('[')) return false;
  const next = text.slice(1).trimStart()[0];
  return next === '{' || next === '"' || next === '[' || next === ']';
};

/** Lines that carry no data: blank, or a comment the example itself is full of. */
const isSkippable = (line) => !line.trim() || line.trim().startsWith('#');

/** `[weapons]` opens a section. Anything else is data. */
const sectionOf = (line) => {
  const m = /^\s*\[\s*([a-z0-9_]+)\s*\]\s*$/i.exec(line);
  return m ? m[1].toLowerCase() : null;
};

/**
 * Which character separates the columns.
 *
 * Tabs win outright when present, because a tab in a pasted table came from a spreadsheet
 * or a PDF and is never punctuation. Otherwise it is whichever of comma and semicolon
 * appears more - Excel writes semicolons wherever the regional list separator is one, and
 * a GM in Germany should not have to know that.
 */
const delimiterOf = (text) => {
  if (text.includes('\t')) return '\t';
  const commas = (text.match(/,/g) || []).length;
  const semis = (text.match(/;/g) || []).length;
  return semis > commas ? ';' : ',';
};

/**
 * One delimited line, honouring quotes.
 *
 * `"Kit, Cyberdoc"` is one cell. `""` inside a quoted cell is a literal quote. Anything
 * outside quotes splits on the delimiter. A line with an unclosed quote is reported by the
 * caller rather than swallowing the rest of the file.
 */
const splitRow = (line, delimiter) => {
  const cells = [];
  let cell = '';
  let quoted = false;
  let closed = true;

  for (let i = 0; i < line.length; i += 1) {
    const ch = line[i];
    if (quoted) {
      if (ch === '"') {
        if (line[i + 1] === '"') { cell += '"'; i += 1; } else { quoted = false; closed = true; }
      } else cell += ch;
    } else if (ch === '"' && cell.trim() === '') {
      quoted = true;
      closed = false;
      cell = '';
    } else if (ch === delimiter) {
      cells.push(cell.trim());
      cell = '';
    } else cell += ch;
  }
  cells.push(cell.trim());
  return { cells, closed };
};

/** A price a GM typed: `1,000`, `$500`, `2.5k` is not supported but `2500` is. */
const readPrice = (raw) => {
  const text = String(raw == null ? '' : raw).trim().replace(/[$£€\s,]/g, '');
  if (!text) return null;
  const n = Number(text);
  if (!Number.isFinite(n) || n < 0) return null;
  return n;
};

/**
 * An id for a row, from its name.
 *
 * Generated rather than asked for. A GM transcribing a book table should not also have to
 * invent stable identifiers, and a name is what the sheet stores anyway - which is what
 * ownedItems matches on when the thing is later sold.
 */
const slug = (name) => String(name || '').trim().toLowerCase()
  .replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');

/** Turn one row of values into a catalogue entry, or say what is wrong with it. */
const readRow = (catalogue, columns, cells, line, problems) => {
  const values = {};
  columns.forEach((col, i) => { values[col] = (cells[i] ?? '').trim(); });

  const name = (values.name || '').trim();
  if (!name) {
    problems.push({ line, catalogue, message: 'no name, so there is nothing to sell' });
    return null;
  }

  const price = readPrice(values.price);
  if (price === null) {
    problems.push({
      line, catalogue, name,
      message: `price "${values.price || ''}" is not a number`,
    });
    return null;
  }

  // Everything that is not name or price fills the sheet when the item is bought. Blank
  // cells are dropped rather than stored, so an empty column never overwrites anything.
  const fields = {};
  for (const col of columns) {
    if (col === 'name' || col === 'price') continue;
    if (values[col]) fields[col] = values[col];
  }

  return { id: slug(name), name, price, fields, line };
};

/** JSON in, in either of the two shapes somebody would reasonably write. */
const parseJson = (text, problems) => {
  let data;
  try {
    data = JSON.parse(text);
  } catch (err) {
    problems.push({ line: 0, message: `not valid JSON: ${err.message}` });
    return {};
  }

  const sections = {};
  const take = (catalogue, rows) => {
    if (!Array.isArray(rows)) {
      problems.push({ line: 0, catalogue, message: 'expected a list of items' });
      return;
    }
    const out = [];
    rows.forEach((row, i) => {
      if (!row || typeof row !== 'object') {
        problems.push({ line: i + 1, catalogue, message: 'not an item' });
        return;
      }
      const columns = Object.keys(row);
      const cells = columns.map((c) => (row[c] == null ? '' : String(row[c])));
      const entry = readRow(catalogue, columns, cells, i + 1, problems);
      if (entry) out.push(entry);
    });
    sections[catalogue] = out;
  };

  if (Array.isArray(data)) {
    // One flat list, each row naming its own catalogue.
    const grouped = {};
    data.forEach((row, i) => {
      const catalogue = row && row.catalogue ? String(row.catalogue) : '';
      if (!catalogue) {
        problems.push({ line: i + 1, message: 'no catalogue on this row' });
        return;
      }
      (grouped[catalogue] ||= []).push(row);
    });
    Object.entries(grouped).forEach(([c, rows]) => take(c, rows));
  } else if (data && typeof data === 'object') {
    Object.entries(data).forEach(([c, rows]) => take(c, rows));
  } else {
    problems.push({ line: 0, message: 'expected an object or a list' });
  }
  return sections;
};

/** The sectioned delimited format the example is written in. */
const parseDelimited = (text, problems) => {
  const delimiter = delimiterOf(text);
  const lines = text.split(/\r\n|\r|\n/);
  const sections = {};

  let catalogue = null;
  let columns = null;

  lines.forEach((raw, i) => {
    const line = i + 1;
    if (isSkippable(raw)) return;

    const opened = sectionOf(raw);
    if (opened) {
      catalogue = opened;
      columns = null;
      sections[catalogue] ||= [];
      return;
    }

    const { cells, closed } = splitRow(raw, delimiter);
    if (!closed) {
      problems.push({ line, catalogue, message: 'a quote is opened and never closed' });
      return;
    }

    if (!catalogue) {
      problems.push({ line, message: 'a row before any [section], so nothing knows what it is' });
      return;
    }

    // The first data row of a section names its columns.
    if (!columns) {
      columns = cells.map((c) => c.trim().toLowerCase());
      if (!columns.includes('name')) {
        problems.push({ line, catalogue, message: 'the header has no name column' });
        columns = null;
      } else if (!columns.includes('price')) {
        problems.push({ line, catalogue, message: 'the header has no price column' });
        columns = null;
      }
      return;
    }

    const entry = readRow(catalogue, columns, cells, line, problems);
    if (entry) sections[catalogue].push(entry);
  });

  return sections;
};

/**
 * Read a catalogue, whatever the GM gave us.
 *
 * Returns `{ sections, problems, format }`. `sections` is catalogue id -> entries, and is
 * whatever could be read - a file with problems still yields the rows that were fine, so a
 * preview can show both at once.
 */
const parseCatalogue = (input) => {
  const problems = [];
  const text = stripBom(String(input == null ? '' : input)).trim();
  if (!text) return { sections: {}, problems: [{ line: 0, message: 'nothing to read' }], format: null };

  const json = looksLikeJson(text);
  const sections = json ? parseJson(text, problems) : parseDelimited(text, problems);

  // Two rows of one thing is a GM editing in a hurry, not a catalogue with two prices for
  // a pistol. Later wins, and they are told.
  for (const [catalogue, rows] of Object.entries(sections)) {
    const seen = new Map();
    for (const row of rows) {
      if (seen.has(row.id)) {
        problems.push({
          line: row.line, catalogue, name: row.name,
          message: `a second "${row.name}"; the later one is used`,
        });
      }
      seen.set(row.id, row);
    }
    sections[catalogue] = [...seen.values()];
  }

  return { sections, problems, format: json ? 'json' : 'delimited' };
};

module.exports = {
  parseCatalogue, splitRow, delimiterOf, readPrice, slug, stripBom, looksLikeJson,
};
